env:
  node: true
  es6: true
extends:
  - 'eslint:recommended'
parserOptions:
  ecmaVersion: 2017
  ecmaFeatures:
    experimentalObjectRestSpread: true
  sourceType: module
rules:
  quotes:
    - warn
    - single
  semi:
    - warn
    - never
  curly:
    - warn
    - multi-or-nest
  arrow-parens:
    - warn
    - as-needed
  no-unused-vars:
    - warn
    - args: none
  no-console: off
  linebreak-style: off
  no-case-declarations: off
